title: Demo Magento 2 on AWS
tag: 1.0.5
type: free
artifakt_version: "0.1"
description: Demo Magento 2 on AWS using Bitnami image.
cloud_provider: aws
build_engine: terraform
available_regions:
  - sa-east-1
  - eu-west-3
  - eu-west-2
  - eu-west-1
  - eu-central-1
  - ca-central-1
  - ap-northeast-1
  - ap-southeast-2
  - ap-southeast-1
  - ap-northeast-2
  - ap-south-1
  - us-west-2
  - us-west-1
  - us-east-2
  - us-east-1
image: https://assets.artifakt.io/platforms/logo-magento-1.png
category: e_commerce
main_language: php
license:
   code: mit
   name: MIT
tags:
  - magento
  - AWS
  - bitnami
  - demo 
  - e-commerce
infrastructure:
  diagram: https://assets.artifakt.io/platforms/platform-demo-app-aws.png
  build_time: 50 #seconds
  cost_estimation:
    monthly_price: 18.30  #in dollars per month
    details: Price calculated using t2.small instance and 8GB HDD in Ireland.
outputs:
  -
    code: public_url
    name: public URL
    description: Fully qualified URL
    category: url
actions:
  -
    code: deploy
    name: Deploy
    description: Deploy magento code 
    category: deploy
    engine: shell
    script: deploy.sh
  -
    code: rollback
    name: Rollback
    description: Rollback magento code 
    category: deploy
    engine: shell
    script: rollback.sh
  -
    code: flush
    name: Flush
    description: Flush magento cache 
    category: cache
    engine: shell
    script: flush.sh
  -
    code: warmup
    name: Warmup
    description: Warmup magento cache 
    category: cache
    engine: shell
    script: warmup.sh
inputs:
  - 
    code: dbname
    name: Database name
    description: Choose your database name
    category: data
    type: text
    default: mydbname
    required:  true
  - 
    code: dbsize
    name: Database size
    description: Choose your database size
    category: data
    type: text
    default: t2.micro
    required:  true
  - 
    code: server_number
    name: Server number
    description: Choose your server number
    category: server
    type: text
    default: "1"
    required:  true
