title: Demo Magento 2 on AWS 
type: free
description: Demo Magento 2 on AWS using Bitnami image.
cloud_provider: aws
build_engine: terraform
available_regions:
  - sa-east-1
  - eu-west-3
  - eu-west-2
  - eu-west-1
  - eu-central-1
  - ca-central-1
  - ap-northeast-1
  - ap-southeast-2
  - ap-southeast-1
  - ap-northeast-2
  - ap-south-1
  - us-west-2
  - us-west-1
  - us-east-2
  - us-east-1
image: https://assets.artifakt.io/platforms/logo-magento-1.png
category: e_commerce
main_language: php
license:
   code: mit
   name: MIT
tags:
  - magento
  - AWS
  - bitnami
  - demo 
  - e-commerce
infrastructure:
  diagram: https://assets.artifakt.io/platforms/platform-demo-app-aws.png
  build_time: 50 #seconds
  cost_estimation:
    monthly_price: 18.30  #in dollars per month
    details: Price calculated using t2.small instance and 8GB HDD in Ireland.
outputs:
  -
    code: public_url
    name: public URL
    description: Fully qualified URL
    category: url
